/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package com.revature.khealy;

import jakarta.servlet.Servlet;
import org.apache.catalina.LifecycleException;
import org.apache.catalina.startup.Tomcat;

import jakarta.servlet.Servlet;
import jakarta.servlet.http.HttpServlet;
import org.apache.catalina.LifecycleException;
import org.apache.catalina.startup.Tomcat;

public class App {


    private static String filename = new String("npd.csv");
    //"C:\\Users\\kevin\\PRPT\\Server\\app\\src\\main\\resources\\npd.csv"
    //C:\Users\kevin\PRPT\Server\



    public static void main(String[] args){
        //String filename = args[0];
        Pokedex pokedex = new Pokedex(filename);
        DexService dexService = new DexService(pokedex);
        DexServer dexServer = new DexServer(dexService);

        Tomcat server = new Tomcat();
        server.getConnector();
        server.addContext("",null);
        server.addServlet("","dexServlet", (Servlet) dexService).addMapping("/");
        try {
            this.server.start();
        } catch (
                LifecycleException e) {
            e.printStackTrace();
        }

    }
}
