/*
 * This Java source file was generated by the Gradle 'init' task.
 */

/*
package com.revature.khealy;

import org.testng.annotations.Test;
import static org.junit.jupiter.api.Assertions.*;
import static org.testng.Assert.assertNotNull;

class AppTest {
    @Test void appHasAGreeting() {
        App classUnderTest = new App();
        //assertNotNull(classUnderTest.getGreeting(), "app should have a greeting");
    }
}
*/