/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package Server;

public class App {


    private static String filename = new String("C:\\Users\\kevin\\PRPT\\Server\\app\\src\\main\\resources\\npd.csv");
    //
    //C:\Users\kevin\PRPT\Server\


    public static void main(String[] args){
        //String filename = args[0];
        Pokedex pokedex = new Pokedex(filename);
        DexService dexService = new DexService(pokedex);
        DexServer dexServer = new DexServer(dexService);
        //server.run(pokedex);
    }
}
